# Docs:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - /modules/azure-landing-zone/*
    - /components/global/*
    

variables:
  terraformVersion: 0.12.26
  agentPool: 'ubuntu-18.04'
  build: $(Build.BuildNumber)
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  action:


parameters:
  - name: environments
    type: object
    default:
    - deployment: 'sbox_cftapps_cluster_lb'
      environment: 'sbox'
      component: 'cftapps_cluster_lb'
      service_connection: 'dcd-cftapps-sbox'
      storage_account_rg: 'core-infra-sbox-rg'
      storage_account_name: 'cftappssbox'
      dependsOn: 'Precheck'

    - deployment: 'sbox_cftapps_cluster_lb_backend'
      environment: 'sbox'
      component: 'cftapps_cluster_lb_backend'
      service_connection: 'dcd-cftapps-sbox'
      storage_account_rg: 'core-infra-sbox-rg'
      storage_account_name: 'cftappssbox'
      dependsOn: 'Precheck'

    - deployment: 'sbox_shutter'
      environment: 'sbox'
      component: 'shutter'
      service_connection: 'dcd-cftapps-sbox'
      storage_account_rg: 'core-infra-sbox-rg'
      storage_account_name: 'cftappssbox'
      dependsOn: 'Precheck'

    - deployment: 'sbox_compliance'
      environment: 'sbox'
      component: 'compliance'
      service_connection: 'dcd-cftapps-sbox'
      storage_account_rg: 'core-infra-sbox-rg'
      storage_account_name: 'cftappssbox'
    
    # - deployment: 'ptl_dynatrace_activegate'
    #   environment: 'ptl'
    #   component: 'dynatrace_activegate'
    #   service_connection: 'DTS-CFTPTL-INTSVC'
    #   storage_account_rg: 'core-infra-intsvc-rg'
    #   storage_account_name: 'cftptlintsvc'
    #   dependsOn: 'Precheck'

    # - deployment: 'ithc_cftapps_cluster_lb'
    #   environment: 'ithc'
    #   component: 'cftapps_cluster_lb'
    #   service_connection: 'dcd-cftapps-ithc'
    #   storage_account_rg: 'core-infra-ithc-rg'
    #   storage_account_name: 'cftappsithc'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'ithc_cftapps_cluster_lb_backend'
    #   environment: 'ithc'
    #   component: 'cftapps_cluster_lb_backend'
    #   service_connection: 'dcd-cftapps-ithc'
    #   storage_account_rg: 'core-infra-ithc-rg'
    #   storage_account_name: 'cftappsithc'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'ldata_cftapps_cluster_lb'
    #   environment: 'ldata'
    #   component: 'cftapps_cluster_lb'
    #   service_connection: 'azurerm-ethosldata'
    #   storage_account_rg: 'core-infra-ldata-rg'
    #   storage_account_name: 'ethosldata'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'ldata_cftapps_cluster_lb_backend'
    #   environment: 'ldata'
    #   component: 'cftapps_cluster_lb_backend'
    #   service_connection: 'azurerm-ethosldata'
    #   storage_account_rg: 'core-infra-ldata-rg'
    #   storage_account_name: 'ethosldata'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'demo_cftapps_cluster_lb_backend'
    #   environment: 'demo'
    #   component: 'cftapps_cluster_lb_backend'
    #   service_connection: 'dcd-cftapps-demo'
    #   storage_account_rg: 'core-infra-demo-rg'
    #   storage_account_name: 'cftappsdemo'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'test_cftapps_cluster_lb'
    #   environment: 'test'
    #   component: 'cftapps_cluster_lb'
    #   service_connection: 'dcd-cftapps-test'
    #   storage_account_rg: 'core-infra-test-rg'
    #   storage_account_name: 'cftappstest'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'test_cftapps_cluster_lb_backend'
    #   environment: 'test'
    #   component: 'cftapps_cluster_lb_backend'
    #   service_connection: 'dcd-cftapps-test'
    #   storage_account_rg: 'core-infra-test-rg'
    #   storage_account_name: 'cftappstest'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'stg_cftapps_cluster_lb'
    #   environment: 'stg'
    #   component: 'cftapps_cluster_lb'
    #   service_connection: 'dcd-cftapps-stg'
    #   storage_account_rg: 'core-infra-stg-rg'
    #   storage_account_name: 'cftappsstg'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'stg_cftapps_cluster_lb_backend'
    #   environment: 'stg'
    #   component: 'cftapps_cluster_lb_backend'
    #   service_connection: 'dcd-cftapps-stg'
    #   storage_account_rg: 'core-infra-stg-rg'
    #   storage_account_name: 'cftappsstg'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'prod_cftapps_cluster_lb'
    #   environment: 'prod'
    #   component: 'cftapps_cluster_lb'
    #   service_connection: 'dcd-cftapps-prod'
    #   storage_account_rg: 'core-infra-prod-rg'
    #   storage_account_name: 'cftappsprod'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'prod_cftapps_cluster_lb_backend'
    #   environment: 'prod'
    #   component: 'cftapps_cluster_lb_backend'
    #   service_connection: 'dcd-cftapps-prod'
    #   storage_account_rg: 'core-infra-prod-rg'
    #   storage_account_name: 'cftappsprod'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

    # - deployment: 'prod_shutter' 
    #   environment: 'prod'
    #   component: 'shutter'
    #   service_connection: 'dcd-cftapps-prod'
    #   storage_account_rg: 'core-infra-prod-rg'
    #   storage_account_name: 'cftappsprod'
    #   dependsOn: 'sbox_cftapps_cluster_lb'

stages:
  - stage: Precheck
    jobs:
      - job: Validate
        pool: ${{ variables.agentPool }}
        steps:
        - task: AzureKeyVault@1
          displayName: Retrieve keyvault secret for ADO token
          inputs:
            ConnectedServiceName: azurerm-sandbox
            keyVaultName: infra-vault-nonprod
            secretsFilter: 'azure-devops-token'
            runAsPreJob: false
        - task: Bash@3
          displayName: Prevent parallel run
          env:
            thisbuild: $(Build.BuildId)
            pipelinedefinition: $(System.DefinitionId)
            azuredevopstoken: $(azure-devops-token)
          inputs:
            filePath: pipeline-scripts/builds-check.sh


  - ${{ each deployment in parameters.environments }}:
    - stage: ${{ deployment.deployment }}
      dependsOn: ${{ deployment.dependsOn }}
      jobs:
        - template: pipeline-templates/terraform.yaml
          parameters:       
            environment: ${{ deployment.environment }}
            component: ${{ deployment.component }}
            service_connection: ${{ deployment.service_connection }}
            storage_account_rg: ${{ deployment.storage_account_rg }}
            storage_account_name: ${{ deployment.storage_account_name }}
            build: ${{ variables.build }}
            terraformVersion: ${{ variables.terraformVersion }}
            timeoutInMinutes: 60
            pool:   
              vmImage: ${{ parameters.pool }}